# #####################################################################
# Automatically generated by qmake (2.01a) to 2. okt 23:22:11 2008
# #####################################################################
TEMPLATE = lib
CONFIG += plugin
HEADERS = xqdeplugin_analogclock.h \
    ../../xqdeenvironment.h
SOURCES = xqdeplugin_analogclock.cpp
DESTDIR = ../../plugins
